version: '3.1'
services:
    etl:
        image: python:3.10
    db:
        env_file: .env
        image: postgres:14.2
        restart: always
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
          - 5432:5432